name: Take-Action

on:
  push:
    branch:
      - main

jobs:
  create-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Just run
        run: echo "Hello World"
